- name: Install dependencies
  apt:
    name:
      - automake
      - autotools-dev
      - bsdmainutils
      - build-essential
      - cargo
      - curl
      - git
      - libboost-filesystem-dev
      - libboost-system-dev
      - libboost-test-dev
      - libboost-thread-dev
      - libevent-dev
      - libssl-dev
      - libtool
      - pkg-config
      - ufw
    state: present

- name: Configure UFW firewall
  ufw:
    rule: allow
    port: ssh

- name: Ensure SSH service is enabled
  service:
    name: ssh
    enabled: yes
    state: started

- name: Create home folder for bitcoin user
  become: true
  user:
    name: bitcoin
    createhome: yes

- name: Create home folder for electrs user
  become: true
  user:
    name: electrs
    createhome: yes
